controllers/SystemAdminController.php
<?php

namespace app\controllers;

use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\ModelhistorySearch;
use mdm\admin\models\searchs\User as UserSearch;
use yii\web\NotFoundHttpException;
use Yii;


class SystemAdminController extends \yii\web\Controller
{

    

    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
        
    }

    public function actionViewUser($id)
    {
        return $this->render('view-user', [
            'model' => $this->findModelUser($id),
        ]);
    }

    public function actionUpdateUser($id)
    {
        $model = $this->findModelUser($id);

        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            // Change role
            // $auth = Yii::$app->authManager;
            // $current_role = $auth->getRole($model->user_role);
            // $auth->revokeAll($model->id);
            // $auth->assign($current_role, $model->id);

            return $this->redirect(['view-user', 'id' => $model->id]);
        }

        return $this->render('update-user', [
            'model' => $model,
        ]);
    }

    public function actionDeleteUser($id)
    {
        // Revoke auth_assignment
        $auth = Yii::$app->authManager;        
        $auth->revokeAll($id);
        
        $this->findModelUser($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModelUser($id)
    {
        if (($model = \app\models\User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    

}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\SignupForm;
use app\models\ChangePassword;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;


class UserController extends \yii\web\Controller
{
    /**
     * Signup new user
     * @return string
     */

    

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->getRequest()->post())) {
            // Data for flash message
            $new_user['login'] = mb_strtolower($model->username);
            $new_user['password'] = $model->password;
            

            if ($user = $model->signup()) {
                
                Yii::$app->session->setFlash('new-user-success', $new_user);
                
                return $this->refresh();
            }
        }

        return $this->render('signup', [
                'model' => $model,
        ]);
    }
    /**
     * Change password
     * @return string
     */
    public function actionChangePassword()
    {
        $model = new ChangePassword();
        
        if ($model->load(Yii::$app->getRequest()->post()) && $model->change()) {
            return $this->goHome();
        }

        $this->layout = 'main';

        return $this->render('change-password', [
                'model' => $model,
        ]);
    }

}

views/system-admin/_form-user.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\UserGrid */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-grid-form">
  


        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>

      

        

        

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    
</div>

views/system-admin/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\bootstrap\Alert;

use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\TblProjects */

$this->title = 'Пользователи';
// $this->params['breadcrumbs'][] = ['label' => 'Tbl Projects', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;

?>
<div class="system-admin-view">

    <div class="row">

        <div class="col pt-4">
            <div class="container-fluid">
                <div class="row">
                    <div class="col mt-4">
                    <p>
                        <?= Html::a('Добавить пользователя', ['/user/signup'], ['class' => 'btn btn-primary']) ?>
                    </p>

                            <?= GridView::widget([
                                'dataProvider' => $dataProvider,
                                'layout'=>"<span class='float-right'>$this->title</span>{summary}\n{items}\n{pager}",
                                'filterModel' => $searchModel,
                                'columns' => [
                                    ['class' => 'yii\grid\SerialColumn'],

                                    'id',
                                    'username',
                                    // 'auth_key',
                                    // 'password_hash',
                                    // 'password_reset_token',
                                    //'email:email',
                                    //'status',
                                    //'created_at',
                                    // 'updated_at',
                                    'full_name',
                                   

                                    [
                                        'class' => 'yii\grid\ActionColumn',

                                        'urlCreator' => function ($action, $model, $key, $index) {
                                            if ($action === 'view') {
                                                $url ='view-user?id='.$model->id;
                                                return $url;
                                            }
                                
                                            if ($action === 'update') {
                                                $url ='update-user?id='.$model->id;
                                                return $url;
                                            }
                                            if ($action === 'delete') {
                                                $url ='delete-user?id='.$model->id;
                                                return $url;
                                            }
                                
                                        }
                                    ],
                                ],
                            ]); ?>

                    </div>
                    
                </div>
                
            </div>
        </div>

    </div>

    



</div>

views/system-admin/update-user.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UserGrid */

$this->title = 'Обновление пользователя: ' . $model->full_name;

?>
<div class="user-grid-update">
    <h1 class="text-center mt-3"><?= Html::encode($this->title) ?></h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 mt-3">
                <?= $this->render('_form-user', [
                    'model' => $model,
                ]) ?>
            </div>
        </div>
    </div>





</div>

views/system-admin/view-user.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UserGrid */

$this->title = "Просмотр пользователя: " . $model->full_name;

?>
<div class="user-grid-view">

<h1 class="text-center mt-3"><?= Html::encode($this->title) ?></h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-7 mt-3">
                <p>
                    <?= Html::a('Обновить', ['update-user', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                    <?= Html::a('Удалить', ['delete-user', 'id' => $model->id], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ]) ?>
                </p>

                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'id',
                            'username',
                            'email:email',
                            'created_at',
                            'updated_at',
                            'full_name',
                            
                        ],
                    ]) ?>
            </div>
        </div>
    </div>

    

    

</div>