models/Projects.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "projects".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $description
 * @property string|null $participants
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 */
class Projects extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'projects';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['managers', 'workers', 'created_at', 'updated_at'], 'safe'],
            [['managers', 'workers'], 'required'],
            [['created_by', 'updated_by'], 'default', 'value' => null],
            [['created_by', 'updated_by'], 'integer'],
            [['title'], 'string', 'max' => 255],
           
        ];
    }

    public function behaviors()
    {
        return [

            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],

            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => function () {
                    return date('Y-m-d H:i:s');
                },
            ]
            
        ];
    }

    public function afterFind() {
        parent::afterFind();
        $this->managers = \yii\helpers\Json::decode($this->managers);
        $this->workers = \yii\helpers\Json::decode($this->workers);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Наименование',
            'description' => 'Описание',
            'managers' => 'Менеджмент',
            'workers' => 'Исполнители',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата обновления',
            'created_by' => 'Создал',
            'updated_by' => 'Обновил',
        ];
    }
}

controllers/ProjectsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Projects;
use app\models\ProjectsSearch;
use app\models\Sprints;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProjectsController implements the CRUD actions for Projects model.
 */
class ProjectsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Projects models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjectsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Projects models.
     * @return mixed
     */
    public function actionBacklog($id)
    {
        $searchModel = new ProjectsSearch();
        $dataProvider = $searchModel->searchBacklog(Yii::$app->request->queryParams);
        $sprints = Sprints::find()->select(['id', 'title'])->orderBy('id')->where(['project_id' => $id])->asArray()->all();
       

        return $this->render('backlog', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'sprints' => $sprints,
            'id' => $id
        ]);
    }

    /**
     * Displays a single Projects model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Projects model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Projects();
       
        if (Yii::$app->request->isPost && $model->load(Yii::$app->request->post())) {
           
            $model->managers = \yii\helpers\Json::encode($model->managers); 
            $model->workers = \yii\helpers\Json::encode($model->workers); 
            $model->save();
            
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Projects model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->request->isPost && $model->load(Yii::$app->request->post())) {

            $model->managers = \yii\helpers\Json::encode($model->managers); 
            $model->workers = \yii\helpers\Json::encode($model->workers); 
            $model->save();

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Projects model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Projects model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Projects the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Projects::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SprintsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sprints;
use app\models\SprintWithTasks;
use app\models\SprintsTasks;
use app\models\Tasks;
use app\models\SprintsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SprintsController implements the CRUD actions for Sprints model.
 */
class SprintsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Sprints models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SprintsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Sprints models.
     * @return mixed
     */
    public function actionSprintPlan($sprint_id)
    {
        $searchModel = new SprintsSearch();
        $dataProvider = $searchModel->searchPlan(Yii::$app->request->queryParams);
        $for_columns = $dataProvider->allModels;
       
        
        $table_columns = array_keys($for_columns[0]);
        // delete sprint_id column
        unset($table_columns[1]);
        // dx($dataProvider);

        return $this->render('sprint_plan', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'table_columns' => $table_columns
        ]);
    }

    public function actionUpdatePlan($sprint_id)
    {
        // Get parametrs
        $request = Yii::$app->request;
        $new_plan = $request->post('new_plan');
        $new_fact = $request->post('new_fact');
        $current_task = $request->post('current_task');

        // Get model
        $sprints_docs = SprintsTasks::findOne(['task_id' => $current_task, 'sprint_id' => $sprint_id]);
        $sprints_docs->plan = $new_plan;
        $sprints_docs->fact = $new_fact;
        $sprints_docs->updateAttributes(['plan', 'fact']);

        // Return Grind-view
        $searchModel = new SprintsSearch();
        $dataProvider = $searchModel->searchPlan(Yii::$app->request->queryParams);
        $for_columns = $dataProvider->allModels;
       
        
        $table_columns = array_keys($for_columns[0]);
        // delete sprint_id column
        unset($table_columns[1]);
        // dx($dataProvider);

        return $this->render('sprint_plan', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'table_columns' => $table_columns
        ]);

        
        

    }

    /**
     * Displays a single Sprints model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Sprints model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($project_id)
    {
        $model = new SprintWithTasks();
        $model->project_id = $project_id;

        if($model->load(Yii::$app->request->post())){
            if ($model->save()) {
                $model->saveTasks();
                return $this->redirect(['/projects/backlog', 'id' => $project_id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'project_id' => $project_id,
            'tasks' => Tasks::getAvailableTasks(),
        ]);
    }

    /**
     * Updates an existing Sprints model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = SprintWithTasks::findOne($id);
        $model->loadTasks();

        if($model->load(Yii::$app->request->post())){
            if ($model->save()) {
                $model->saveTasks();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'project_id' => $model->project_id,
            'tasks' => Tasks::getAvailableTasks(),
        ]);
    }

    /**
     * Deletes an existing Sprints model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Sprints model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Sprints the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Sprints::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/TasksController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tasks;
use app\models\TasksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TasksController implements the CRUD actions for Tasks model.
 */
class TasksController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tasks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TasksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tasks model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tasks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($project_id)
    {
        $model = new Tasks();
        $model->project_id = $project_id;
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/projects/backlog', 'id' => $project_id]);
        }

        return $this->render('create', [
            'model' => $model,
            'project_id' => $project_id
        ]);
    }

    /**
     * Updates an existing Tasks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tasks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tasks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tasks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tasks::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/projects/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true, 'autocomplete' => "off"]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?php // $form->field($model, 'participants')->textInput() ?>
    <?php
        $users = ArrayHelper::map(\app\models\User::find()->select(['id', 'full_name'])->orderBy('full_name')->asArray()->all(), 'id', 'full_name');
        // dx($users);
        echo $form->field($model, 'managers')->widget(Select2::classname(), [
            'data' => $users,
            'options' => ['placeholder' => 'Выберите менеджеров...'],
            'pluginOptions' => [
                'allowClear' => true,
                'multiple' => true
            ],
            'pluginEvents' => [
                "select2:opening" => "function() { 
                    //Get value from workers select
                    let selected_options = $('#projects-workers').val(); 

                    //Get all options from managers select
                    let managers_options = $('#projects-managers').find('option');

                    //For each managers_option compare with selected_options
                    managers_options.each(function( index ) {
                        if(selected_options.indexOf($( this ).val()) != -1)
                        {  
                            $( this ).prop('disabled', true);
                        }else{
                            $( this ).prop('disabled', false);

                        }
                      
                      });                   
                }",                
            ]
        ]);

        echo $form->field($model, 'workers')->widget(Select2::classname(), [
            'data' => $users,
            'options' => ['placeholder' => 'Выберите исполнителей...'],
            'pluginOptions' => [
                'allowClear' => true,
                'multiple' => true
            ],
            'pluginEvents' => [
                "select2:opening" => "function() { 
                    //Get value from managers select
                    let selected_options = $('#projects-managers').val(); 

                    //Get all options from workers select
                    let workers_options = $('#projects-workers').find('option');

                    //For each workers_option compare with selected_options
                    workers_options.each(function( index ) {
                        if(selected_options.indexOf($( this ).val()) != -1)
                        {  
                            $( this ).prop('disabled', true);
                        }else{
                            $( this ).prop('disabled', false);

                        }
                      
                      });                   
                }",                
            ]
        ]);
    ?>
   

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projects/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProjectsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'participants') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projects/backlog.php
<?php

use Codeception\PHPUnit\ResultPrinter\HTML as ResultPrinterHTML;
use yii\bootstrap4\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;


/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Бэклог';
$this->params['breadcrumbs'][] = $this->title;

       
// dx(empty($dataProvider)); 

?>
<div class="projects-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <hr>

    <p>
        <?= Html::a('Создать задачу', ['tasks/create', 'project_id' => $id], ['class' => 'btn btn-success']) ?>
        
        <?php if(empty($dataProvider)): ?>
            <?= Html::button('Создать спринт',  ['class' => 'btn btn-primary', 'disabled'=>true]) ?>

        <?php else: ?>
            <?= Html::a('Создать спринт', ['sprints/create', 'project_id' => $id], ['class' => 'btn btn-primary']) ?>
        <?php endif ?>
        <span class="float-right"><button class="btn btn-secondary" id="export-table">Экспорт ExCel</button></span>
    </p>


    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?php
    // GridView::widget([
    //     'dataProvider' => $dataProvider,
    //     // 'filterModel' => $searchModel,
    //     'beforeHeader'=>[
    //         [
    //             'columns'=>[
    //                 // ['content'=>'Header Before 1', 'options'=>['colspan'=>4, 'class'=>'text-center warning']], 
    //                 ['content'=>'', 'options'=>['colspan'=>2, 'class'=>'text-center warning']], 
    //                 ['content'=>'Спринт 1', 'options'=>['colspan'=>2, 'class'=>'text-center warning']], 
    //             ],
    //             'options'=>['class'=>'skip-export'] // remove this row from export
    //         ]
    //     ],

    //     'columns' => [
    //         //['class' => 'yii\grid\SerialColumn'],


    //         [
    //             'attribute'=>'task_id',
    //             'label'=> 'Пункт'
    //         ],

    //         [
    //             'attribute'=>'task_title',
    //             'label'=> 'Задача'
    //         ],
    //         'plans',
    //         'facts'


    //         // ['class' => 'yii\grid\ActionColumn'],
    //     ],
    // ]); 

    ?>

    <?php
        $sprints_ids = ArrayHelper::getColumn($sprints, 'id');
        // dx(empty($dataProvider));

    ?>

    <table class="table table-bordered" id="my-grid-id">
        <thead>
            <tr>
                <td colspan="2"></td>
                <?php foreach ($sprints as $sprint) : ?>
                    <th colspan="2"><?= Html::a($sprint['title'], ['sprints/sprint-plan', 'sprint_id' => $sprint['id']]) ?></th>
                <?php endforeach ?>
            </tr>
            <tr>
                <th scope="col-4">Пункт</th>
                <th scope="col-8">Задача</th>
                <?php foreach ($sprints as $sprint) : ?>
                    <th scope="row">План</th>
                    <th scope="row">Факт</th>
                <?php endforeach ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($dataProvider as $task) : ?>
                <tr>
                    <th scope="row"><?= $task['id'] ?></th>
                    <td><?= $task['title'] ?></td>
                    <?php foreach ($sprints_ids as $id) : ?>
                        <?php if(array_key_exists($id, $task['sprints'])): ?>
                            <td scope="row"><?= $task['sprints'][$id]['plan'] ?></td>
                            <td scope="row"><?= $task['sprints'][$id]['fact'] ?></td>
                        <?php else: ?>
                            <td scope="row"></td>
                            <td scope="row"></td>
                        <?php endif ?>
                        
                    <?php endforeach ?>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>


</div>

<?php
$this->registerJsFile("@web/template/js/tableToExcel.js",[
    'depends' => [
        \yii\web\JqueryAsset::className()
    ]
]);
?>

<?php
$js = <<< JS


    $('#export-table').click(function () {
    
        TableToExcel.convert(document.getElementById("my-grid-id"));
        

    });

JS;

$this->registerJs($js, $position = yii\web\View::POS_READY, $key = null);
?>

views/projects/create.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = 'Создать проект';
$this->params['breadcrumbs'][] = ['label' => 'Проекты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-create">

    <h1 class="text-center mt-3"><?= Html::encode($this->title) ?></h1>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 mt-3">
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
            </div>
        </div>
    </div>


</div>

views/projects/index.php
<?php

use Codeception\PHPUnit\ResultPrinter\HTML as ResultPrinterHTML;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Проекты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать проект', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute'=>'title',
                'format' => 'raw',
                'value'=>function($data){
                    return HTML::a($data->title, ['backlog', 'id'=>$data->id]);
                }
            ],
            'description:ntext',
            // 'participants',
            [
                'attribute'=>'managers',
                'filter'=>'',
                'value'=>function($data){
                    $result = [];
                    foreach($data->managers as $manager_id){
                        $full_name = app\models\User::findOne($manager_id)->full_name;
                        $result[] = $full_name;
                    }
                    return implode(", ", $result);
                }
            ],
            [
                'attribute'=>'workers',
                'filter'=>'',
                'value'=>function($data){
                    $result = [];
                    foreach($data->workers as $manager_id){
                        $full_name = app\models\User::findOne($manager_id)->full_name;
                        $result[] = $full_name;
                    }
                    return implode(", ", $result);
                }
            ],
            
            'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/projects/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = 'Обновление проекта: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Проекты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить проект';
?>
<div class="projects-update">

    <h1 class="text-center mt-3"><?= Html::encode($this->title) ?></h1>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 mt-3">
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
            </div>
        </div>
    </div>

</div>

views/projects/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="projects-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'description:ntext',
          
            [
                'attribute'=>'managers',
                'value'=>function($data){
                    $result = [];
                    foreach($data->managers as $manager_id){
                        $full_name = app\models\User::findOne($manager_id)->full_name;
                        $result[] = $full_name;
                    }
                    return implode(", ", $result);
                }
            ],
            [
                'attribute'=>'workers',
                'value'=>function($data){
                    $result = [];
                    foreach($data->workers as $manager_id){
                        $full_name = app\models\User::findOne($manager_id)->full_name;
                        $result[] = $full_name;
                    }
                    return implode(", ", $result);
                }
            ],

            'created_at',
            'updated_at',
            'created_by',
            'updated_by',
        ],
    ]) ?>

</div>