models/Sprints.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "sprints".
 *
 * @property int $id
 * @property string|null $title
 * @property int|null $project_id
 * @property string|null $begint_date
 * @property string|null $end_date
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property int|null $plan
 * @property int|null $fact
 * @property int|null $interval
 *
 * @property Projects $project
 * @property SprintsTasks[] $sprintsTasks
 */
class Sprints extends \yii\db\ActiveRecord
{
    public $plan;
    public $fact;
    public $interval;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sprints';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['project_id', 'created_by', 'updated_by'], 'default', 'value' => null],
            [['project_id', 'created_by', 'updated_by', 'plan', 'fact'], 'integer'],
            [['begint_date', 'end_date', 'created_at', 'updated_at', 'interval'], 'safe'],
            [['title'], 'string', 'max' => 255],
            [['project_id'], 'exist', 'skipOnError' => true, 'targetClass' => Projects::className(), 'targetAttribute' => ['project_id' => 'id']],
        ];
    }

    public function behaviors()
    {
        return [

            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],

            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => function () {
                    return date('Y-m-d H:i:s');
                },
            ]
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Наименование',
            'project_id' => 'Проект',
            'begint_date' => 'Дата начала',
            'end_date' => 'Дата окончания',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата обновления',
            'created_by' => 'Создал',
            'updated_by' => 'Обновил',
        ];
    }

    /**
     * Gets query for [[Project]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProject()
    {
        return $this->hasOne(Projects::className(), ['id' => 'project_id']);
    }

    /**
     * Gets query for [[SprintsTasks]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSprintsTasks()
    {
        return $this->hasMany(SprintsTasks::className(), ['sprint_id' => 'id']);
    }
}

controllers/SprintsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sprints;
use app\models\SprintWithTasks;
use app\models\SprintsTasks;
use app\models\Tasks;
use app\models\SprintsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SprintsController implements the CRUD actions for Sprints model.
 */
class SprintsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Sprints models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SprintsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Sprints models.
     * @return mixed
     */
    public function actionSprintPlan($sprint_id)
    {
        $searchModel = new SprintsSearch();
        $dataProvider = $searchModel->searchPlan(Yii::$app->request->queryParams);
        $for_columns = $dataProvider->allModels;
       
        
        $table_columns = array_keys($for_columns[0]);
        // delete sprint_id column
        unset($table_columns[1]);
        // dx($dataProvider);

        return $this->render('sprint_plan', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'table_columns' => $table_columns
        ]);
    }

    public function actionUpdatePlan($sprint_id)
    {
        // Get parametrs
        $request = Yii::$app->request;
        $new_plan = $request->post('new_plan');
        $new_fact = $request->post('new_fact');
        $current_task = $request->post('current_task');

        // Get model
        $sprints_docs = SprintsTasks::findOne(['task_id' => $current_task, 'sprint_id' => $sprint_id]);
        $sprints_docs->plan = $new_plan;
        $sprints_docs->fact = $new_fact;
        $sprints_docs->updateAttributes(['plan', 'fact']);

        // Return Grind-view
        $searchModel = new SprintsSearch();
        $dataProvider = $searchModel->searchPlan(Yii::$app->request->queryParams);
        $for_columns = $dataProvider->allModels;
       
        
        $table_columns = array_keys($for_columns[0]);
        // delete sprint_id column
        unset($table_columns[1]);
        // dx($dataProvider);

        return $this->render('sprint_plan', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'table_columns' => $table_columns
        ]);

        
        

    }

    /**
     * Displays a single Sprints model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Sprints model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($project_id)
    {
        $model = new SprintWithTasks();
        $model->project_id = $project_id;

        if($model->load(Yii::$app->request->post())){
            if ($model->save()) {
                $model->saveTasks();
                return $this->redirect(['/projects/backlog', 'id' => $project_id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'project_id' => $project_id,
            'tasks' => Tasks::getAvailableTasks(),
        ]);
    }

    /**
     * Updates an existing Sprints model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = SprintWithTasks::findOne($id);
        $model->loadTasks();

        if($model->load(Yii::$app->request->post())){
            if ($model->save()) {
                $model->saveTasks();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'project_id' => $model->project_id,
            'tasks' => Tasks::getAvailableTasks(),
        ]);
    }

    /**
     * Deletes an existing Sprints model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Sprints model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Sprints the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Sprints::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/sprints/_form.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Sprints */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sprints-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'project_id', ['enableClientValidation' => false])->dropdownList(
        ArrayHelper::map(\app\models\Projects::find()->select(['id', 'title'])->asArray()->all(), 'id', 'title'),
        [
            'options' => [$project_id => ['Selected' => 'selected']],
            'prompt' => 'Выберите проект',
            'disabled' => 'disabled'
        ]
    ); ?>

    <?= $form->field($model, 'begint_date')->widget(DatePicker::classname(), [
        'removeButton' => false,
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'options' => ['placeholder' => 'Дата начала спринта', 'autocomplete' => "off"],
        'pluginOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd'
        ]
    ]) ?>

    <?= $form->field($model, 'end_date')->widget(DatePicker::classname(), [
        'removeButton' => false,
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'options' => ['placeholder' => 'Дата окончания спринта', 'autocomplete' => "off"],
        'pluginOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd'
        ]
    ]) ?>

    <?= $form->field($model, 'tasks_ids')
        ->listBox($tasks, ['multiple' => true])
        /* or, you may use a checkbox list instead */
        /* ->checkboxList($categories) */
        ->hint('Добавить задачи в спринт');
    ?>



    <div class="form-group">
        <?= Html::submitButton('Создать', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/sprints/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SprintsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sprints-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'project_id') ?>

    <?= $form->field($model, 'begint_date') ?>

    <?= $form->field($model, 'end_date') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/sprints/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Sprints */

$this->title = 'Создать спринт';
$this->params['breadcrumbs'][] = ['label' => 'Бэклог', 'url' => ['projects/backlog', 'id' => $project_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sprints-create">

    <h1 class="text-center mt-3"><?= Html::encode($this->title) ?></h1>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 mt-3">
                <?= $this->render('_form', [
                    'model' => $model,
                    'project_id' => $project_id,
                    'tasks' => $tasks
                ]) ?>
            </div>
        </div>
    </div>

</div>

views/sprints/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SprintsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Sprints';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sprints-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Sprints', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'project_id',
            'begint_date',
            'end_date',
            //'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/sprints/sprint_plan.php
<?php

use yii\bootstrap4\Html;
use yii\grid\GridView;
use yii\bootstrap4\Modal;
use kartik\export\ExportMenu;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SprintsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$items = $dataProvider->allModels;
$current_sprint = \app\models\Sprints::findOne(['id'=> $items[0]['sprint_id']]);

$this->title = $current_sprint->title;

$this->params['breadcrumbs'][] = ['label' => 'Бэклог', 'url' => ['projects/backlog', 'id' => $current_sprint->project_id]];
$this->params['breadcrumbs'][] = $this->title;

$gridColumns = $table_columns;

// dx($dataProvider->allModels);
?>
<div class="sprints-index">





    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <div class="row">
        <div class="col-10">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
        <div class="col-2">
            <?php
                echo ExportMenu::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => $gridColumns,
                    'showConfirmAlert' => false,
                    'fontAwesome' => true,
                    'container' => ['class' => 'btn-group mb-5'],
                    'exportConfig' => [
                        ExportMenu::FORMAT_TEXT => false,
                        ExportMenu::FORMAT_PDF => false,
                        ExportMenu::FORMAT_HTML => false,
                        ExportMenu::FORMAT_CSV => false,
                        ExportMenu::FORMAT_EXCEL => [
                            'icon' => 'fas fa-file-excel'
                        ]
                    ],
                ]);
            ?>
        </div>
    </div>


    <?php



    $searchModel2 = [];
    $searchColumns = [];
    $searchAttributes = $table_columns;
    

    foreach ($searchAttributes as $searchAttribute) {

        $filterName = 'filter' . $searchAttribute;
        $filterValue = Yii::$app->request->getQueryParam($filterName, '');
        $searchModel2[$searchAttribute] = $filterValue;

        $searchColumns[] = [
            'attribute' => $searchAttribute,
            'filter' => '<input class="form-control" name="' . $filterName . '" value="' . $filterValue . '" type="text">',
            'value' => $searchAttribute,
        ];

        $items = array_filter($items, function ($item) use (&$filterValue, &$searchAttribute) {
            return strlen($filterValue) > 0 ? stripos('/^' . strtolower($item[$searchAttribute]) . '/', strtolower($filterValue)) : true;
        });
    }

    ?>

    <?= GridView::widget([

        // 'layout' => "<span class='float-right'>$this->title</span>{summary}\n{items}\n{pager}",
        // 'filterModel' => $searchModel,

        'tableOptions' => [
            'class' => 'table table-striped table-bordered',
            'id' => 'table_sprint_plan'
        ],

        'dataProvider' => new \yii\data\ArrayDataProvider([
            'allModels' => $items,
            'sort' => [
                'attributes' => $searchAttributes,
            ],
        ]),
        'filterModel' => $searchModel2,
        'columns' => $searchColumns

    ]); ?>

    <!-- Модальное окно rename FILE -->
    <?php
    Modal::begin([
        'title' => 'Обновить',
        'titleOptions' => ['class' => 'ml-auto'],
        'closeButton' => ['class' => 'close text-white'],
        'size' => 'modal-lg modal-dialog-centered',
        'options' => ['id' => 'modal-update-plan'],
    ]);
    ?>


    <?= Html::beginForm(['/sprints/update-plan', 'sprint_id' => $items[0]['sprint_id']], 'post', ['data-pjax' => '', 'id' => 'form-update-plan']); ?>
    <?= Html::hiddenInput('current_task') ?>
    <div class="form-group row">
        <label class="col-sm-4">Обновить План</label>
        <div class="col-sm-8">
            <?= Html::input('text', 'new_plan', null, ['class' => 'form-control', 'autocomplete' => "off"]) ?>
            <div class="invalid-feedback">
                Использованы запрещенные символы [. <'>`"].
            </div>
        </div>
    </div>

    <div class="form-group row">

        <label class="col-sm-4">Обновить Факт</label>
        <div class="col-sm-8">
            <?= Html::input('text', 'new_fact', null, ['class' => 'form-control', 'autocomplete' => "off"]) ?>
            <div class="invalid-feedback">
                Использованы запрещенные символы [. <'>`"].
            </div>
        </div>

    </div>

    <div class="row justify-content-center">
        <?= Html::button('Сохранить', ['class' => 'btn btn-success', 'onclick' => 'updatePlan()']) ?>
        <?= Html::button('Назад', ['class' => 'ml-3 btn btn-secondary', 'data-dismiss' => 'modal']) ?>
    </div>

    <?= Html::endForm() ?>

    <?php Modal::end(); ?>

    <!-- Модальное окно загрузки файла -->


</div>

<script>
    function updatePlan() {
        $("#form-update-plan").submit();

    }
</script>

<?php
$js = <<< JS


    $( "#table_sprint_plan tr:not(.filters)" ).dblclick(function() {
        let task_id = $(this).find('td:first').text();
        let sprint_id = $("input[name='current_task']").val(task_id);
        // console.log(sprint_id);
        $('#modal-update-plan').modal('show');
    });

    

JS;

$this->registerJs($js, $position = yii\web\View::POS_READY, $key = null);
?>

views/sprints/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Sprints */

$this->title = 'Обновить спринт ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Бэклог', 'url' => ['projects/backlog', 'id' => $project_id]];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить спринт';
?>
<div class="sprints-update">

    <h1 class="text-center mt-3"><?= Html::encode($this->title) ?></h1>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 mt-3">
                <?= $this->render('_form', [
                    'model' => $model,
                    'project_id' => $project_id,
                    'tasks' => $tasks
                ]) ?>
            </div>
        </div>
    </div>

</div>

views/sprints/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Sprints */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Sprints', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="sprints-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'project_id',
            'begint_date',
            'end_date',
            'created_at',
            'updated_at',
            'created_by',
            'updated_by',
        ],
    ]) ?>

</div>